name: Generate Datas 
on: 
  schedule: # выполнить каждые 12 часов 
    - cron: "* */12 * * *" 
  workflow_dispatch: 
jobs: 
  build: 
    name: Jobs to update datas 
    run-on: ubuntu-latest 
    steps: 
      # Snake Animation 
      — использует: Platane/snk@master 
        id: змея-gif
с: 
          github_user_name: EkaterinaKononenko 
          svg_out_path: dist/github-contribution-grid-snake.svg 
      — использует: crazy-max/ghaction-github-pages@v2.1.3 
        с: 
          target_branch: output 
          build_dir: dist 
        env: 
          GITHUB_TOKEN: ${{ secrets .GITHUB_TOKEN }}
